#!/bin/bash

#g++ for cvte-decoder
g++ -std=c++11 -I../include -I/home/qing/project/kaldi/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/qing/project/kaldi/tools/ATLAS/include -msse -msse2 -pthread -g  -fPIC   -c -o cvte-decoder.o cvte-decoder.cc 
g++  -Wl,-rpath=/home/qing/project/kaldi/tools/openfst/lib -rdynamic -Wl,-rpath=/home/qing/project/kaldi/src/lib cvte-decoder.o ../libs/libkaldi-online2.so ../libs/libkaldi-ivector.so ../libs/libkaldi-nnet3.so ../libs/libkaldi-chain.so ../libs/libkaldi-nnet2.so ../libs/libkaldi-cudamatrix.so ../libs/libkaldi-decoder.so ../libs/libkaldi-lat.so ../libs/libkaldi-fstext.so ../libs/libkaldi-hmm.so ../libs/libkaldi-feat.so ../libs/libkaldi-transform.so ../libs/libkaldi-gmm.so ../libs/libkaldi-tree.so ../libs/libkaldi-util.so ../libs/libkaldi-matrix.so ../libs/libkaldi-base.so /home/qing/project/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -o cvte-decoder

#g++ for online-cvte-decoder.o
#g++ -std=c++11 -I../include -I/home/qing/project/kaldi/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/qing/project/kaldi/tools/ATLAS/include -msse -msse2 -pthread -g  -fPIC   -c -o online-cvte-decoder.o online-cvte-decoder.cc 
#g++  -Wl,-rpath=/home/qing/project/kaldi/tools/openfst/lib -rdynamic -Wl,-rpath=/home/qing/project/kaldi/src/lib online-cvte-decoder.o ../libs/libkaldi-online2.so ../libs/libkaldi-ivector.so ../libs/libkaldi-nnet3.so ../libs/libkaldi-chain.so ../libs/libkaldi-nnet2.so ../libs/libkaldi-cudamatrix.so ../libs/libkaldi-decoder.so ../libs/libkaldi-lat.so ../libs/libkaldi-fstext.so ../libs/libkaldi-hmm.so ../libs/libkaldi-feat.so ../libs/libkaldi-transform.so ../libs/libkaldi-gmm.so ../libs/libkaldi-tree.so ../libs/libkaldi-util.so ../libs/libkaldi-matrix.so ../libs/libkaldi-base.so /home/qing/project/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -o online-cvte-decoder

